export const animals = [
  {
    name: "Bella",
    color: "chromatic",
    category: "cat",
    breed: "Ragdoll",
    img: "https://kittentoob.com/wp-content/uploads/2015/03/ragdoll-640x368.jpg",
    age: "8mth",
    gender: "female",
    price: 120,
    about:
      "With its long silky coat and bright blue eyes, it's no wonder the ragdoll tops the list as the most popular cat breed for the third year in a row. Living up to its namesake, the ragdoll is known to go limp in your arms and will soak up all the love and cuddles you have to offer. These cooperative kitties are kind and do well with children, making them the perfect cat companion for your entire clan.",
  },
  {
    name: "Bella",
    color: "white",
    category: "cat",
    breed: "Exotic",
    img: "https://i.pinimg.com/564x/f7/fa/73/f7fa73999ddd4fb2b31ced36b9192a4e.jpg",
    age: "8mth",
    gender: "female",
    price: 120,
    about:
      "Though they bear a strikingly similar resemblance to their parent breed, the Persian, the exotic is evidently more popular, likely due to its low-maintenance mane. Minimal upkeep is required to keep these felines looking—and feeling—fancy. When it comes to grooming, one brush through weekly should do the trick, Keiger says.",
  },
  {
    name: "Bella",
    color: "black",
    category: "cat",
    breed: "Main Coon",
    img: "https://i2.wp.com/felineliving.net/wp-content/uploads/2020/01/0-3-1024x661.jpg",
    age: "8mth",
    gender: "female",
    price: 120,
    about: `"Our largest breed, the Maine coon cat deservedly earned the nickname of 'the gentle giant,'" Keiger says. "Someone who has never seen one is often surprised at just how large they are; a male can be 20 pounds and all muscle."
      In other words, these large cats have even more to love! Better yet, they have a lot of their own love to give and are highly regarded as one of the friendliest cat breeds you can find.`,
  },
  {
    name: "Bella",
    color: "orange",
    category: "cat",
    breed: "Main Coon",
    breedCharacteristics: "",
    img: "https://thumbs.dreamstime.com/z/ginger-maine-coon-cat-orange-beanbag-ginger-maine-coon-cat-big-orange-beanbag-195043194.jpg",
    age: "8mth",
    gender: "female",
    price: 120,
    about: `"Our largest breed, the Maine coon cat deservedly earned the nickname of 'the gentle giant,'" Keiger says. "Someone who has never seen one is often surprised at just how large they are; a male can be 20 pounds and all muscle."
      In other words, these large cats have even more to love! Better yet, they have a lot of their own love to give and are highly regarded as one of the friendliest cat breeds you can find.`,
  },
  {
    name: "Bella",
    category: "cat",
    breed: "Persian",
    breedCharacteristics: "",
    color: "white",
    img: "https://www.petmd.com/sites/default/files/styles/article_image/public/white-persian-cats-picture-id637190306.jpg?itok=UZI3pQwD",
    age: "8mth",
    gender: "female",
    price: 120,
    about:
      "Flat faces and long, flowing fur make the popular Persian one of the most recognizable breeds around the world. Despite their regal appearance, Persians don't need a whole lot to be happy and are often most satisfied cuddled in your lap. Their long hair, however, does require consistent maintenance and should be brushed daily to avoid uncomfortable mats.",
  },
  {
    name: "Bella",
    category: "cat",
    breed: "Persian",
    breedCharacteristics: "",
    color: "orange",
    img: "https://vetstreet.brightspotcdn.com/dims4/default/7cc218c/2147483647/thumbnail/645x380/quality/90/?url=https%3A%2F%2Fvetstreet-brightspot.s3.amazonaws.com%2Fa5%2F69%2Fe639b7ab40c2a290e3296de726d8%2FPersian-AP-PIFN6J-645sm3614.jpg",
    age: "8mth",
    gender: "female",
    price: 120,
    about:
      "Flat faces and long, flowing fur make the popular Persian one of the most recognizable breeds around the world. Despite their regal appearance, Persians don't need a whole lot to be happy and are often most satisfied cuddled in your lap. Their long hair, however, does require consistent maintenance and should be brushed daily to avoid uncomfortable mats.",
  },
  {
    name: "Milo",
    color: "yellow",
    category: "dog",
    breed: "Labrador Retriever",
    img: "https://www.rover.com/blog/wp-content/uploads/2020/06/Labrador-Retriever-2.jpg",
    age: "9mth",
    gender: "male",
    price: 120,
    about: `You may already know the Labrador Retriever as a high-energy, water-loving family dog. You might also feel like you see them everywhere. That’s no coincidence because the Labrador Retriever is one of the most popular dogs in the United States (and in much of the world). Read on to learn more about this easy going dog breed, from their hunting dog history to how to care for your very own lab best friend, and decide whether a Labrador Retriever dog is right for you.`,
  },
  {
    name: "Milo",
    color: "gold",
    category: "dog",
    breed: "Golden Retriever",
    img: "https://www.rover.com/blog/wp-content/uploads/2020/06/Golden-Retriever-2.jpg",
    age: "9mth",
    gender: "male",
    price: 120,
    about: `You may know Golden Retrievers by their signature color, gorgeous feathering, floppy ears, or sunny dispositions. These water-loving, playful pups were originally bred to retrieve fowl for hunters, but these days, they’re happy in many other roles, too, from playing endless fetch with their owners to working as service dogs`,
  },
  {
    name: "Milo",
    color: "tan/black",
    category: "dog",
    breed: "German Shepherd",
    age: "9mth",
    gender: "male",
    price: 120,
    img: `https://www.rover.com/blog/wp-content/uploads/2020/06/German-Shepherd-1-1024x683.jpg`,
    about: `German Shepherd dogs are known by their wolf-like appearance, strength, loyalty, and noble disposition. They were originally bred to herd sheep and protect flocks from danger, but German Shepherds are so much more than working dogs.`,
  },
  {
    name: "Milo",
    color: "tan/black",
    category: "dog",
    breed: "Australian Shepherd",
    age: "9mth",
    gender: "male",
    price: 120,
    img: `https://www.rover.com/blog/wp-content/uploads/2020/06/Australian-Shepherd-2.jpg`,
    about: `Athletic, devoted, and smart, smart, smart: it’s the Australian Shepherd! Aussies are a working breed originally developed for sheep herding. These days, they’re still put to Sork on ranches all around the world, but they’re also beloved companion dogs and among the most popular breeds. They’re loyal companions with a lot of love and affection to give…so long as they get enough exercise. `,
  },
  {
    name: "Milo",
    color: "gold",
    category: "dog",
    breed: "Goldendoodle",
    age: "9mth",
    gender: "male",
    price: 120,
    img: `https://www.rover.com/blog/wp-content/uploads/2021/06/groverdood-1024x768.jpg`,
    about: `Part Golden retriever, part Poodle, and all adorable…it’s the Goldendoodle! They are a hybrid breed beloved for their outgoing nature, friendly personality, and intelligence. They’re relatively new, gaining popularity since the 1990’s alongside other cross-breeds like Cockapoos and Labradoodles. Back in the day, they were thought to be hypoallergenic. These days, we know that they may or may not be better for allergies depending on the dog and the person; but most do have soft, wavy fur that sheds less than other dogs. They’re also one of the most popular breeds in the country.`,
  },
  {
    name: "Dave",
    color: "grey",
    category: "bird",
    breed: "African Grey",
    img: "https://www.thesprucepets.com/thmb/P0aUiJYxz1VzZgcvNS7HwBC1kSs=/4444x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/close-up-of-african-grey-parrot-673167809-5b4d137bc9e77c001aaeec57.jpg",
    age: "1yr",
    gender: "male",
    price: 120,
    about: `The intelligence and emotional capacity of African greys are often compared to that of a 5-year-old human. But bear in mind these birds don't move past the maturity of a 5-year-old for their entire lifespan of around 50 years or more. A bored, unattended African grey can quickly become a destructive escape artist. Because of the bird's intellect, many caretakers constantly have to find new ways to keep their pets occupied.`,
  },
  {
    name: "Dave",
    color: "white",
    category: "bird",
    breed: "Umbrella Cockatoo",
    img: "https://www.thesprucepets.com/thmb/L0oyB2KzMPzEBXnldcmx0ka1m58=/5075x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-522664558-58ad90123df78c345b8667b1.jpg",
    age: "1yr",
    gender: "male",
    price: 120,
    about: `With proper care, umbrella cockatoos can live 70 to 80 years or more in captivity. These birds tend to be gentle and sweet, forming strong bonds with their caretakers. Many love to cuddle up to their favorite person (or bird) and can be distraught whenever they are separated. So it’s important to have enough time to spend with these smart, social birds.`,
  },
  {
    name: "Dave",
    color: "yellow",
    category: "bird",
    breed: "Yellow-Naped Amazon",
    img: "https://www.thesprucepets.com/thmb/_7VpQDRgWlQd9yzjV_3Ss9xgnRM=/5472x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/yellow-napped-parrot--amazona-auropalliata---costa-rica-540176970-5b4d1430c9e77c00379d7787.jpg",
    age: "1yr",
    gender: "male",
    price: 120,
    about: `The yellow-naped Amazon—one of the best talkers in the parrot family—makes a fine avian companion. These birds have sunny dispositions, bonding closely with their caretakers. But anyone thinking of adopting one should be aware these birds can live more than 70 years if properly cared for. This isn't a commitment to be taken lightly.`,
  },
  {
    name: "Dave",
    color: "white",
    category: "bird",
    breed: "Sulphur-Crested Cockatoo",
    img: "https://www.thesprucepets.com/thmb/FTJ701VjVJNmBlBL9jLYumX8kHI=/4912x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/close-up-of-sulphur-crested-cockatoo-on-field-600801451-5b4d141246e0fb0037376158.jpg",
    age: "1yr",
    gender: "male",
    price: 120,
    about: `With a lengthy lifespan of around 80 years, the sulphur-crested cockatoo comes in two sizes. The greater sulphur-crested cockatoo measures around 20 inches from beak to tail while the lesser sulphur-crested cockatoo measures around 15 inches. Like other cockatoos, these birds have a reputation for being very affectionate and need to spend ample time with their caretakers.`,
  },
  {
    name: "Dave",
    color: "blue/red",
    category: "bird",
    breed: "Blue-and-Gold Macaw",
    img: "https://www.thesprucepets.com/thmb/izNP1iRZFzgAUUNRSdp1WHphILU=/2082x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/blue-and-yellow-macaws--ara-ararauna---pair--native-to-south-america--captive--wachenheim--germany-999155090-5b4d121dc9e77c00549c58fd.jpg",
    age: "1yr",
    gender: "male",
    price: 120,
    about: `With a lifespan upward of 50 years in captivity, the blue-and-gold macaw is a large parrot that has enjoyed immense popularity as a pet. These colorful birds are extremely intelligent and often take well to learning tricks and how to talk. They have strong personalities and are happiest in homes with experienced parrot owners who can give them ample out-of-cage playtime.`,
  },
];
